version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 5
  similar-code:
    config:
      threshold: 250 # not number of lines, but mass threshold (see default analysis configuration)
  identical-code:
    config:
      threshold: 250 # not number of lines, but mass threshold (see default analysis configuration)
  file-lines:
    config:
      threshold: 300

exclude_patterns:
  - "**/test/"
  - "**/androidTest/"
  - "**test"
